version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  service-activity-tracking:
    lang: node12
    handler: ./src
    image: santig/service-activity-tracking:latest
